import type {FastifyInstance,FastifyRequest} from 'fastify';
import type {PoolClient} from 'pg';
import {randomBytes,randomInt,randomUUID,timingSafeEqual} from 'node:crypto';
import {z} from 'zod';
import {actor,limit} from './auth.js';
import {audit,fail,manage,tx} from './db.js';
import {digest} from './crypto.js';
import {plate} from '../shared/contracts.js';

const station=z.string().regex(/^[a-z0-9-]{3,40}$/),phone=z.string().regex(/^\+[1-9][0-9]{7,14}$/),otp=z.string().regex(/^\d{6}$/);
const identify=z.object({station,plate}).strict(),verify=identify.extend({challenge_id:z.uuid(),code:otp}).strict();
const customer=z.object({name:z.string().trim().min(2).max(80),phone_e164:phone,plate,label:z.string().trim().max(40).optional()}).strict();
const mask=(value:string)=>value.length<5?'••••':`${value.slice(0,3)}${'•'.repeat(Math.max(4,value.length-7))}${value.slice(-4)}`;
const findVehicle=async(c:PoolClient,slug:string,value:string)=>(await c.query('select o.id organization_id,c.id customer_id,c.name,c.phone_e164 from app.organizations o join app.customer_vehicles v on v.organization_id=o.id join app.customers c on c.id=v.customer_id and c.organization_id=o.id where o.slug=$1 and v.plate=$2 and v.active and c.active',[slug,value])).rows[0];
async function summary(c:PoolClient,org:string,customerId:string,value:string){const p=(await c.query('select name,phone_e164 from app.customers where id=$1 and organization_id=$2 and active',[customerId,org])).rows[0];if(!p)fail(404,'Customer not found');const balance=(await c.query('select coalesce(sum(points),0)::text balance from app.points_ledger where organization_id=$1 and plate=$2',[org,value])).rows[0].balance,history=(await c.query('select id,quantity_ml,amount_paise,points,fraud,created_at from app.transactions where organization_id=$1 and plate=$2 order by created_at desc limit 25',[org,value])).rows;return {plate:value,name:p.name,masked_phone:mask(p.phone_e164),balance,history};}
async function trusted(req:FastifyRequest,org:string,customerId:string){const token=req.cookies.fp_customer;if(!token)return false;return tx(async c=>!!(await c.query('update app.customer_sessions set last_used_at=now() where token_hash=$1 and organization_id=$2 and customer_id=$3 and trusted_until>now() returning token_hash',[digest(token),org,customerId])).rows[0]);}
async function sendOtp(to:string,code:string){const sid=process.env.TWILIO_ACCOUNT_SID,token=process.env.TWILIO_AUTH_TOKEN,from=process.env.TWILIO_FROM;if(!sid||!token||!from)fail(503,'Customer OTP service is not configured yet');const body=new URLSearchParams({To:to,From:from,Body:`Your FuelPulse verification code is ${code}. It expires in 10 minutes.`}),url='https:'+'//api.twilio.com/2010-04-01/Accounts/'+encodeURIComponent(sid)+'/Messages.json',response=await fetch(url,{method:'POST',headers:{authorization:`Basic ${Buffer.from(`${sid}:${token}`).toString('base64')}`,'content-type':'application/x-www-form-urlencoded'},body});if(!response.ok)fail(502,'Unable to send verification code');}

export function customerRoutes(app:FastifyInstance){
 app.get('/api/vehicle-lookup',async req=>{const a=await actor(req),q=z.object({plate}).strict().parse(req.query);return tx(async c=>{const row=(await c.query('select c.name,c.phone_e164 from app.customer_vehicles v join app.customers c on c.id=v.customer_id and c.organization_id=v.organization_id where v.plate=$1 and v.active and c.active',[q.plate])).rows[0];if(!row)return {registered:false,plate:q.plate};const balance=(await c.query('select coalesce(sum(points),0)::text balance from app.points_ledger where plate=$1',[q.plate])).rows[0].balance,last=(await c.query('select created_at from app.transactions where plate=$1 order by created_at desc limit 1',[q.plate])).rows[0];return {registered:true,plate:q.plate,name:row.name,masked_phone:mask(row.phone_e164),balance,last_visit:last?.created_at??null};},a);});
 app.get('/api/customers',async req=>{const a=await actor(req);manage(a);return tx(async c=>(await c.query("select c.id,c.name,c.phone_e164,c.active,coalesce(json_agg(json_build_object('id',v.id,'plate',v.plate,'label',v.label,'active',v.active) order by v.plate) filter(where v.id is not null),'[]') vehicles from app.customers c left join app.customer_vehicles v on v.customer_id=c.id and v.organization_id=c.organization_id group by c.id order by c.name")).rows,a);});
 app.post('/api/customers',async req=>{const a=await actor(req);manage(a);const b=customer.parse(req.body);return tx(async c=>{const owner=(await c.query('insert into app.customers(organization_id,name,phone_e164) values($1,$2,$3) returning id',[a.organization_id,b.name,b.phone_e164])).rows[0],vehicle=(await c.query('insert into app.customer_vehicles(organization_id,customer_id,plate,label) values($1,$2,$3,$4) returning id',[a.organization_id,owner.id,b.plate,b.label??null])).rows[0];await audit(c,a,'customer.created',owner.id);return {id:owner.id,vehicle_id:vehicle.id};},a);});
 app.post('/api/customer/identify',async req=>{const b=identify.parse(req.body),found=await tx(c=>findVehicle(c,b.station,b.plate));if(!found)fail(404,'Registered vehicle not found');if(await trusted(req,found.organization_id,found.customer_id))return tx(c=>summary(c,found.organization_id,found.customer_id,b.plate));return {trusted:false,plate:b.plate,masked_phone:mask(found.phone_e164)};});
 app.post('/api/customer/request-otp',async req=>{const b=identify.parse(req.body),account=digest(`${b.station}:${b.plate}`),ip=digest(req.ip);const made=await tx(async c=>{const accountAllowed=await limit(c,'customer:a:'+account,5),ipAllowed=await limit(c,'customer:i:'+ip,30);if(!accountAllowed||!ipAllowed)return null;const found=await findVehicle(c,b.station,b.plate);if(!found)fail(404,'Registered vehicle not found');const id=randomUUID(),code=String(randomInt(0,1000000)).padStart(6,'0');await c.query("insert into app.customer_otp_challenges(id,organization_id,customer_id,plate,code_hash,expires_at) values($1,$2,$3,$4,$5,now()+interval '10 minutes')",[id,found.organization_id,found.customer_id,b.plate,digest(`${id}:${code}`)]);return {...found,id,code};});if(!made)fail(429,'Too many verification attempts; try again later');try{await sendOtp(made.phone_e164,made.code);}catch(error){await tx(c=>c.query('delete from app.customer_otp_challenges where id=$1',[made.id]));throw error;}return {challenge_id:made.id,masked_phone:mask(made.phone_e164),expires_in_seconds:600};});
 app.post('/api/customer/verify-otp',async(req,reply)=>{const b=verify.parse(req.body),result=await tx(async c=>{const q=(await c.query("select q.*,o.slug from app.customer_otp_challenges q join app.organizations o on o.id=q.organization_id where q.id=$1 and q.plate=$2 and o.slug=$3 and q.consumed_at is null and q.expires_at>now() for update",[b.challenge_id,b.plate,b.station])).rows[0];if(!q)return {error:'invalid' as const};if(q.attempts>=5)return {error:'limited' as const};const actual=Buffer.from(digest(`${b.challenge_id}:${b.code}`),'hex'),expected=Buffer.from(q.code_hash,'hex');if(actual.length!==expected.length||!timingSafeEqual(actual,expected)){await c.query('update app.customer_otp_challenges set attempts=attempts+1 where id=$1',[b.challenge_id]);return {error:'invalid' as const};}await c.query('update app.customer_otp_challenges set consumed_at=now() where id=$1',[b.challenge_id]);const token=randomBytes(32).toString('hex');await c.query("insert into app.customer_sessions(token_hash,organization_id,customer_id,trusted_until) values($1,$2,$3,now()+interval '30 days')",[digest(token),q.organization_id,q.customer_id]);return {token,data:await summary(c,q.organization_id,q.customer_id,b.plate)};});if('error'in result)fail(result.error==='limited'?429:401,result.error==='limited'?'Too many verification attempts':'Verification code expired or invalid');reply.setCookie('fp_customer',result.token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',path:'/',maxAge:30*24*3600});return result.data;});
 app.post('/api/customer/logout',async(req,reply)=>{if(req.cookies.fp_customer)await tx(c=>c.query('delete from app.customer_sessions where token_hash=$1',[digest(req.cookies.fp_customer!)]));reply.clearCookie('fp_customer',{path:'/'});return {ok:true};});
}
