import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { actor } from "./auth.js";
import { fail, pool, tx, audit } from "./db.js";

const offerBody = z.object({title:z.string().trim().min(2).max(120),description:z.string().trim().max(500).default(""),festival:z.string().trim().max(60).default(""),offer_type:z.enum(["PERCENT","AMOUNT","FREE_FUEL","BONUS_POINTS"]),value:z.number().int().positive(),min_amount_paise:z.number().int().min(0).default(0),fuel_name:z.string().trim().max(60).nullable().optional(),starts_at:z.string().datetime(),ends_at:z.string().datetime(),active:z.boolean().default(true)}).strict();
const manage=(role:string)=>{if(role!=="OWNER"&&role!=="MANAGER")fail(403,"Manager access required")};
export function offerRoutes(app:FastifyInstance){
 app.get("/api/offers",async req=>{const q=z.object({station:z.string().regex(/^[a-z0-9-]{3,40}$/).optional(),all:z.coerce.boolean().default(false)}).parse(req.query);if(q.all){const a=await actor(req);manage(a.role);return tx(async c=>(await c.query("select id,title,description,festival,offer_type,value,min_amount_paise,fuel_name,starts_at,ends_at,active,created_at from app.offers where organization_id=$1 order by starts_at desc,created_at desc",[a.organization_id])).rows,a)}if(!q.station)fail(400,"Station is required");return (await pool.query("select o.id,o.title,o.description,o.festival,o.offer_type,o.value,o.min_amount_paise,o.fuel_name,o.starts_at,o.ends_at from app.offers o join app.organizations g on g.id=o.organization_id where g.slug=$1 and o.active=true and o.starts_at<=now() and o.ends_at>now() order by o.starts_at desc,o.created_at desc",[q.station])).rows});
 app.post("/api/offers",async req=>{const a=await actor(req);manage(a.role);const b=offerBody.parse(req.body);if(b.ends_at<=b.starts_at)fail(400,"Offer end time must be after start time");if(b.offer_type==="PERCENT"&&b.value>100)fail(400,"Percentage offer cannot exceed 100%");return tx(async c=>{const row=(await c.query("insert into app.offers(organization_id,title,description,festival,offer_type,value,min_amount_paise,fuel_name,starts_at,ends_at,active,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) returning *",[a.organization_id,b.title,b.description,b.festival,b.offer_type,b.value,b.min_amount_paise,b.fuel_name||null,b.starts_at,b.ends_at,b.active,a.id])).rows[0];await audit(c,a,"offer.created",row.id);return row},a)});
 app.post("/api/offers/:id",async req=>{const a=await actor(req);manage(a.role);const id=z.string().uuid().parse((req.params as {id:string}).id),b=offerBody.partial().parse(req.body);return tx(async c=>{const existing=(await c.query("select * from app.offers where id=$1 and organization_id=$2",[id,a.organization_id])).rows[0];if(!existing)fail(404,"Offer not found");const next={...existing,...b};if(new Date(next.ends_at)<=new Date(next.starts_at))fail(400,"Offer end time must be after start time");if(next.offer_type==="PERCENT"&&Number(next.value)>100)fail(400,"Percentage offer cannot exceed 100%");const row=(await c.query("update app.offers set title=$1,description=$2,festival=$3,offer_type=$4,value=$5,min_amount_paise=$6,fuel_name=$7,starts_at=$8,ends_at=$9,active=$10 where id=$11 and organization_id=$12 returning *",[next.title,next.description,next.festival,next.offer_type,next.value,next.min_amount_paise,next.fuel_name||null,next.starts_at,next.ends_at,next.active,id,a.organization_id])).rows[0];await audit(c,a,"offer.updated",id);return row},a)});
 app.post("/api/offers/:id/delete",async req=>{const a=await actor(req);manage(a.role);const id=z.string().uuid().parse((req.params as {id:string}).id);return tx(async c=>{const row=(await c.query("delete from app.offers where id=$1 and organization_id=$2 returning id",[id,a.organization_id])).rows[0];if(!row)fail(404,"Offer not found");await audit(c,a,"offer.deleted",id);return {ok:true}},a)});
}
