import type {FastifyInstance} from 'fastify';import {z} from 'zod';import {randomBytes} from 'node:crypto';import {actor,limit} from './auth.js';import {tx,manage,fail,audit} from './db.js';import {submit} from './transactions.js';import {password,plate,coupon} from '../shared/contracts.js';import {hashPassword,verifyPassword,encrypt,decrypt} from './crypto.js';
const uuid=(p:unknown)=>z.object({id:z.string().uuid()}).parse(p).id;
export function routes(app:FastifyInstance){
app.get('/api/catalog',async req=>{const a=await actor(req);return tx(async c=>({organization:(await c.query('select * from app.organizations')).rows[0],pumps:(await c.query('select * from app.pumps order by name')).rows,fuels:(await c.query('select * from app.fuels order by name')).rows,links:(await c.query('select pump_id,fuel_id from app.pump_fuels')).rows}),a);});
app.post('/api/transactions',async req=>{const a=await actor(req);if(req.headers['x-fuelpulse-actor']&&req.headers['x-fuelpulse-actor']!==a.id)fail(409,'Account changed; sign in again');return submit(a,req.body);});
app.get('/api/transactions',async req=>{const a=await actor(req),q=z.object({offset:z.coerce.number().int().min(0).max(1000000).default(0)}).strict().parse(req.query);return tx(async c=>(await c.query('select id,plate,quantity_ml,amount_paise,points,fraud,created_at from app.transactions order by created_at desc,id limit 100 offset $1',[q.offset])).rows,a);});
app.get('/api/dashboard',async req=>{const a=await actor(req);manage(a);return tx(async c=>({metrics:(await c.query("select count(*)::int transactions,coalesce(sum(amount_paise),0)::text revenue,coalesce(sum(quantity_ml),0)::text volume,count(*) filter(where fraud)::int fraud,coalesce(sum(points),0)::text points,count(*) filter(where business_day=(select (now() at time zone timezone)::date from app.organizations))::int today from app.transactions")).rows[0],staff:(await c.query("select count(*)::int n from app.users where active and role='EMPLOYEE'")).rows[0].n,pumps:(await c.query('select count(*)::int n from app.pumps where active')).rows[0].n,coupons:(await c.query('select count(*)::int n from app.coupons where redeemed_at is null and expires_at>now()')).rows[0].n}),a);});
app.get('/api/points',async req=>{const a=await actor(req);manage(a);const q=z.object({plate}).strict().parse(req.query);return tx(async c=>({balance:(await c.query('select coalesce(sum(points),0)::text balance from app.points_ledger where plate=$1',[q.plate])).rows[0].balance,ledger:(await c.query('select transaction_id,points,created_at from app.points_ledger where plate=$1 order by created_at desc limit 100',[q.plate])).rows}),a);});
app.get('/api/staff',async req=>{const a=await actor(req);manage(a);return tx(async c=>(await c.query('select id,name,code,role,active from app.users order by name')).rows,a);});
app.post('/api/staff',async req=>{const a=await actor(req);manage(a);const b=z.object({name:z.string().min(2).max(80),code:z.string().regex(/^[A-Za-z0-9_-]{3,40}$/),role:z.enum(['MANAGER','EMPLOYEE']),password,retrievable:z.boolean().default(false)}).strict().parse(req.body);if(a.role==='MANAGER'&&b.role!=='EMPLOYEE')fail(403,'Not authorized');if(b.retrievable&&!process.env.CREDENTIAL_KEY)fail(409,'Credential retrieval disabled');const hash=await hashPassword(b.password);return tx(async c=>{const u=(await c.query('insert into app.users(organization_id,name,code,role) values($1,$2,$3,$4) returning id',[a.organization_id,b.name,b.code,b.role])).rows[0];await audit(c,a,'staff.created',u.id);await c.query('SET LOCAL ROLE fuelpulse_gateway');await c.query('insert into app.credentials(user_id,password_hash,encrypted_password) values($1,$2,$3)',[u.id,hash,b.retrievable?encrypt(b.password,a.organization_id+':'+u.id):null]);return u;},a);});
app.post('/api/staff/:id',async req=>{const a=await actor(req);manage(a);const id=uuid(req.params),b=z.object({active:z.boolean().optional(),name:z.string().min(2).max(80).optional(),code:z.string().regex(/^[A-Za-z0-9_-]{3,40}$/).optional()}).strict().parse(req.body);return tx(async c=>{const u=(await c.query("update app.users set active=coalesce($1,active),name=coalesce($2,name),code=coalesce($3,code) where id=$4 and role<>'OWNER' returning id",[b.active,b.name,b.code,id])).rows[0];if(!u)fail(404,'Staff not found');await audit(c,a,'staff.updated',id);await c.query('SET LOCAL ROLE fuelpulse_gateway');await c.query('delete from app.sessions where user_id=$1',[id]);return {ok:true};},a);});
app.post('/api/staff/:id/credential',async req=>{const a=await actor(req);manage(a);const id=uuid(req.params),b=z.object({action:z.enum(['retrieve','change']),current:password,next:password.optional(),retrievable:z.boolean().default(false)}).strict().parse(req.body);return tx(async c=>{const u=(await c.query('select role from app.users where id=$1',[id])).rows[0];if(!u||u.role==='OWNER'||a.role==='MANAGER'&&u.role!=='EMPLOYEE')fail(403,'Not authorized');await audit(c,a,'credential.'+b.action,id);await c.query('SET LOCAL ROLE fuelpulse_gateway');if(!await limit(c,'reauth:'+a.id,5))return {error:'Try again later'};const own=(await c.query('select password_hash from app.credentials where user_id=$1',[a.id])).rows[0];if(!await verifyPassword(b.current,own.password_hash))return {error:'Reauthentication failed'};if(b.action==='retrieve'){const row=(await c.query('select encrypted_password from app.credentials where user_id=$1',[id])).rows[0];return row.encrypted_password?{password:decrypt(row.encrypted_password,a.organization_id+':'+id)}:{error:'No retrievable password stored'};}if(!b.next)fail(400,'New password required');await c.query('update app.credentials set password_hash=$1,encrypted_password=$2,updated_at=now() where user_id=$3',[await hashPassword(b.next),b.retrievable?encrypt(b.next,a.organization_id+':'+id):null,id]);await c.query('delete from app.sessions where user_id=$1',[id]);return {ok:true};},a);});
app.post('/api/fuels',async req=>{const a=await actor(req);manage(a);const b=z.object({name:z.string().min(2).max(40),price_paise:z.number().int().min(1).max(100000)}).strict().parse(req.body);return tx(async c=>{await c.query('select pg_advisory_xact_lock(hashtextextended($1,0))',['catalog:'+a.organization_id]);const r=(await c.query('insert into app.fuels(organization_id,name,price_paise) values($1,$2,$3) on conflict(organization_id,name) do update set price_paise=excluded.price_paise returning id',[a.organization_id,b.name,b.price_paise])).rows[0];await audit(c,a,'fuel.price.changed',r.id);return r;},a);});
app.post('/api/pumps',async req=>{const a=await actor(req);manage(a);const b=z.object({name:z.string().min(1).max(60),fuel_ids:z.array(z.string().uuid()).min(1).max(20)}).strict().parse(req.body);return tx(async c=>{await c.query('select pg_advisory_xact_lock(hashtextextended($1,0))',['catalog:'+a.organization_id]);const p=(await c.query('insert into app.pumps(organization_id,name) values($1,$2) returning id',[a.organization_id,b.name])).rows[0];for(const id of new Set(b.fuel_ids))await c.query('insert into app.pump_fuels values($1,$2,$3)',[a.organization_id,p.id,id]);await audit(c,a,'pump.created',p.id);return p;},a);});
app.post('/api/pumps/:id',async req=>{const a=await actor(req);manage(a);const id=uuid(req.params),b=z.object({active:z.boolean()}).strict().parse(req.body);return tx(async c=>{await c.query('select pg_advisory_xact_lock(hashtextextended($1,0))',['catalog:'+a.organization_id]);const p=(await c.query('update app.pumps set active=$1,updated_at=now() where id=$2 returning id',[b.active,id])).rows[0];if(!p)fail(404,'Pump not found');await audit(c,a,'pump.status.changed',id);return p;},a);});
app.post('/api/settings',async req=>{const a=await actor(req);if(a.role!=='OWNER')fail(403,'Not authorized');const b=z.object({points_per_litre:z.number().int().min(0).max(100)}).strict().parse(req.body);return tx(async c=>{await c.query('update app.organizations set points_per_litre=$1 where id=$2',[b.points_per_litre,a.organization_id]);await audit(c,a,'settings.changed');return {ok:true};},a);});
app.get('/api/audit',async req=>{const a=await actor(req);if(a.role!=='OWNER')fail(403,'Not authorized');return tx(async c=>(await c.query('select action,target_id,created_at from app.audit_logs order by created_at desc limit 100')).rows,a);});
app.get('/api/coupons',async req=>{const a=await actor(req);manage(a);return tx(async c=>(await c.query('select * from app.coupons order by created_at desc limit 100')).rows,a);});
app.post('/api/coupons',async req=>{const a=await actor(req);manage(a);const b=z.object({plate,days:z.number().int().min(1).max(90)}).strict().parse(req.body);return tx(async c=>{const r=(await c.query("insert into app.coupons(organization_id,code,plate,expires_at,created_by) values($1,$2,$3,now()+$4*interval '1 day',$5) returning *",[a.organization_id,'FP1:'+randomBytes(24).toString('hex'),b.plate,b.days,a.id])).rows[0];await audit(c,a,'coupon.created',r.id);return r;},a);});
app.post('/api/coupons/redeem',async req=>{const a=await actor(req),b=z.object({code:coupon,plate}).strict().parse(req.body);return tx(async c=>{const r=(await c.query('update app.coupons set redeemed_by=$1,redeemed_at=now() where code=$2 and plate=$3 and redeemed_at is null and expires_at>now() returning id',[a.id,b.code,b.plate])).rows[0];if(!r)fail(409,'Coupon invalid, expired or already redeemed');await audit(c,a,'coupon.redeemed',r.id);return r;},a);});
}
