import {transaction,type Actor} from '../shared/contracts.js';import {tx,fail,audit} from './db.js';import {digest} from './crypto.js';
export async function submit(a:Actor,body:unknown){const b=transaction.parse(body),hash=digest(JSON.stringify(b));return tx(async c=>{
await c.query('select pg_advisory_xact_lock(hashtextextended($1,0))',[`${a.organization_id}:${b.idempotency_key}`]);
const old=(await c.query('select * from app.transactions where organization_id=$1 and idempotency_key=$2',[a.organization_id,b.idempotency_key])).rows[0];if(old){if(old.employee_id!==a.id||old.request_hash!==hash)fail(409,'Idempotency key conflict');return old;}
await c.query('select pg_advisory_xact_lock_shared(hashtextextended($1,0))',[`catalog:${a.organization_id}`]);
const fuel=(await c.query('select f.price_paise from app.fuels f join app.pump_fuels pf on pf.fuel_id=f.id join app.pumps p on p.id=pf.pump_id where f.id=$1 and p.id=$2 and p.active',[b.fuel_id,b.pump_id])).rows[0];if(!fuel)fail(400,'Pump or fuel unavailable');
const org=(await c.query("select points_per_litre,(now() at time zone timezone)::date::text as business_date from app.organizations where id=$1",[a.organization_id])).rows[0];
const n=(await c.query('insert into app.daily_counts(organization_id,pump_id,plate,business_day,n) values($1,$2,$3,$4,1) on conflict(organization_id,pump_id,plate,business_day) do update set n=app.daily_counts.n+1 returning n',[a.organization_id,b.pump_id,b.plate,org.business_date])).rows[0].n;
const fraud=n>=3,points=fraud?0:Math.floor(b.quantity_ml*org.points_per_litre/1000),amount=Math.round(b.quantity_ml*fuel.price_paise/1000);
const result=(await c.query('insert into app.transactions(organization_id,pump_id,employee_id,fuel_id,plate,quantity_ml,price_paise,amount_paise,points,fraud,business_day,idempotency_key,request_hash) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) returning *',[a.organization_id,b.pump_id,a.id,b.fuel_id,b.plate,b.quantity_ml,fuel.price_paise,amount,points,fraud,org.business_date,b.idempotency_key,hash])).rows[0];await c.query('insert into app.points_ledger(organization_id,plate,transaction_id,points) values($1,$2,$3,$4)',[a.organization_id,b.plate,result.id,points]);await audit(c,a,fraud?'transaction.fraud':'transaction.created',result.id);return result;},a);}
