import {useRef,useState} from 'react';
import {api,errorText,money} from './api';
import {scanPlate,type PlateScanner} from './assist';
import './scanner.css';
import './customer.css';

type Summary={plate:string;name:string;masked_phone:string;balance:string;history:{id:string;quantity_ml:number;amount_paise:string;points:number;fraud:boolean;created_at:string}[]};
type Identify=Summary|{trusted:false;plate:string;masked_phone:string};
export function CustomerPortal(){
 const[station,setStation]=useState('fuelpulse-main'),[plate,setPlate]=useState(''),[summary,setSummary]=useState<Summary|null>(null),[masked,setMasked]=useState(''),[challenge,setChallenge]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[scanning,setScanning]=useState(false),[scanMessage,setScanMessage]=useState('Opening camera…');
 const video=useRef<HTMLVideoElement>(null),scanner=useRef<PlateScanner|undefined>(undefined);const stop=()=>{scanner.current?.stop();scanner.current=undefined;setScanning(false);};
 const identify=async(value=plate)=>{setBusy(true);setMessage('');try{const data=await api<Identify>('/customer/identify',{station,plate:value});if('history'in data){setSummary(data);setMasked('');setMessage('Trusted device recognized. No OTP was required.');}else{setSummary(null);setMasked(data.masked_phone);setMessage('First verification on this device requires an OTP.');}}catch(error){setMessage(errorText(error));}finally{setBusy(false);}};
 const start=async()=>{stop();setScanning(true);setScanMessage('Opening camera…');await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));try{if(!video.current)throw Error('Camera unavailable');scanner.current=await scanPlate(video.current,value=>{setPlate(value);setScanning(false);scanner.current=undefined;void identify(value);},value=>setMessage(value),value=>setScanMessage(value));}catch(error){stop();setMessage(errorText(error));}};
 return <main className="customer-page"><section className="panel customer-card"><div className="brand"><b>F</b>FuelPulse</div><p className="eyebrow">VEHICLE OWNER</p><h1>Check your points</h1><p className="muted">The first verification uses an OTP. This phone can then stay trusted for 30 days.</p><form onSubmit={event=>{event.preventDefault();void identify();}}><label>Station ID<input value={station} onChange={event=>setStation(event.target.value)} required/></label><label>Vehicle number<input value={plate} onChange={event=>setPlate(event.target.value.toUpperCase())} required placeholder="MH12AB1234"/></label><button type="button" onClick={scanning?stop:start}>{scanning?'Stop scanner':'Scan my number plate'}</button><div className={`plate-camera ${scanning?'active':''}`} aria-hidden={!scanning}><video ref={video} muted playsInline/><div className="plate-guide"><span>ALIGN NUMBER PLATE HERE</span></div>{scanning&&<div className="scan-status" role="status"><i/>{scanMessage}</div>}</div><button className="primary" disabled={busy}>{busy?'Checking…':'Check points'}</button></form>{masked&&!challenge&&<div className="info"><p>OTP will be sent to <strong>{masked}</strong>.</p><button onClick={async()=>{setBusy(true);try{const data=await api<{challenge_id:string;masked_phone:string}>('/customer/request-otp',{station,plate});setChallenge(data.challenge_id);setMessage(`OTP sent to ${data.masked_phone}`);}catch(error){setMessage(errorText(error));}finally{setBusy(false);}}}>Send OTP</button></div>}{challenge&&!summary&&<form onSubmit={async event=>{event.preventDefault();const code=String(new FormData(event.currentTarget).get('code'));setBusy(true);try{setSummary(await api('/customer/verify-otp',{station,plate,challenge_id:challenge,code}));setChallenge('');setMessage('Verified. This device is trusted for 30 days.');}catch(error){setMessage(errorText(error));}finally{setBusy(false);}}}><label>6-digit OTP<input name="code" inputMode="numeric" pattern="[0-9]{6}" autoComplete="one-time-code" required/></label><button className="primary" disabled={busy}>Verify and trust this device</button></form>}<p role="status">{message}</p>{summary&&<div className="customer-summary"><p className="eyebrow">REGISTERED VEHICLE</p><h2>{summary.plate}</h2><p>{summary.name} · {summary.masked_phone}</p><div className="estimate">{summary.balance} points</div><h3>Recent fills</h3>{summary.history.length?summary.history.map(row=><div className="row" key={row.id}><span>{new Date(row.created_at).toLocaleString('en-IN')}<small>{row.quantity_ml/1000} L</small></span><strong>{money(row.amount_paise)} · +{row.points}</strong></div>):<p className="muted">No confirmed fills yet.</p>}<button onClick={async()=>{await api('/customer/logout',{});setSummary(null);setMessage('Trusted access removed from this device.');}}>Forget this device</button></div>}<p><a href="/">Station staff sign in</a></p></section></main>;
}
