import { ocr, plateCandidates } from "./assist";

type Worker = { recognize:(image:HTMLCanvasElement)=>Promise<{data:{text:string;confidence:number}}>; setParameters:(params:Record<string,string|number>)=>Promise<void>; terminate:()=>Promise<void> };
const workers=new WeakMap<HTMLVideoElement,Promise<Worker>>();
const evidence=new WeakMap<HTMLVideoElement,Map<string,{votes:number;score:number;last:number}>>();
function normalize(v:string){return v.toUpperCase().replace(/[^A-Z0-9]/g,"");}
function compatible(a:string,b:string){if(a===b)return true;const s=a.length<=b.length?a:b,l=a.length<=b.length?b:a;let diff=0;for(let i=0;i<Math.min(a.length,b.length);i++)if(a[i]!==b[i])diff++;return l.startsWith(s)&&l.length-s.length<=2||(a.length===b.length&&a.length>=7&&diff<=1)}
function indianShape(v:string){return /^(?:[A-Z]{2}\d{1,2}[A-Z]{1,3}\d{4}|[A-Z]{2}\d{2,3}[A-Z]{0,3}\d{1,4}|\d{2}BH\d{4}[A-Z]{1,2})$/.test(v)&&v.length>=7;}
async function getWorker(video:HTMLVideoElement){let cached=workers.get(video);if(!cached){cached=import("tesseract.js").then(async({createWorker,PSM})=>{const w=await createWorker("eng",1);await w.setParameters({tessedit_pageseg_mode:PSM.SINGLE_LINE,tessedit_char_whitelist:"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",preserve_interword_spaces:"0"});return w as unknown as Worker;});workers.set(video,cached);}return cached;}
function enhance(c:HTMLCanvasElement,mode:number){const ctx=c.getContext("2d",{willReadFrequently:true});if(!ctx)return;const im=ctx.getImageData(0,0,c.width,c.height),d=im.data;for(let i=0;i<d.length;i+=4){const g=.299*d[i]+.587*d[i+1]+.114*d[i+2];let x=g;if(mode===1)x=g>105?255:0;else if(mode===2)x=g>135?255:0;else if(mode===3)x=g>165?255:0;else if(mode===4)x=Math.max(0,Math.min(255,(g-128)*3+128));d[i]=d[i+1]=d[i+2]=x;}ctx.putImageData(im,0,0);}
export async function fastAlprFrame(video:HTMLVideoElement){if(video.readyState<2||!video.videoWidth)throw Error("Camera not ready");const worker=await getWorker(video),sw=video.videoWidth,sh=video.videoHeight,candidates=new Map<string,number>(),bands=[.22,.34,.46,.58];for(const y of bands){const cw=Math.round(sw*.94),ch=Math.round(sh*.28),cx=Math.round((sw-cw)/2),cy=Math.max(0,Math.min(sh-ch,Math.round(sh*y))),scale=Math.min(3,2400/cw),c=document.createElement("canvas");c.width=Math.max(1,Math.round(cw*scale));c.height=Math.max(1,Math.round(ch*scale));const ctx=c.getContext("2d",{willReadFrequently:true});if(!ctx)continue;ctx.imageSmoothingEnabled=true;ctx.filter="grayscale(1) contrast(1.8)";ctx.drawImage(video,cx,cy,cw,ch,0,0,c.width,c.height);ctx.filter="none";enhance(c,Math.floor(Date.now()/250)%5);const r=await worker.recognize(c);for(const p of plateCandidates(r.data.text)){const v=normalize(p.value);if(v.length<7||v.length>15)continue;const score=p.quality+(r.data.confidence>=70?5:r.data.confidence>=50?3:1)+(indianShape(v)?8:0);candidates.set(v,Math.max(candidates.get(v)??0,score));}}const best=[...candidates.entries()].sort((a,b)=>b[1]-a[1]||b[0].length-a[0].length)[0];if(!best)throw Error("Plate not readable yet");let state=evidence.get(video);if(!state){state=new Map();evidence.set(video,state);}const now=Date.now();for(const [k,v] of state)if(now-v.last>8000)state.delete(k);let hit=[...state.entries()].find(([k])=>compatible(k,best[0]));if(!hit){state.set(best[0],{votes:1,score:best[1],last:now});throw Error(`Reading ${best[0]} · 1 confirmation`);}const item=hit[1];item.votes++;item.score=Math.max(item.score,best[1]);item.last=now;const value=best[0].length>hit[0].length?best[0]:hit[0];if(item.votes<3)throw Error(`Reading ${value} · ${item.votes} confirmations`);return value;}
export async function fastAlprPhoto(file:File){return ocr(file);}
export async function fastAlprWithFallback(file:File,_fallback?: (file:File)=>Promise<string>){return ocr(file);}
