import {useEffect,useState,type FormEvent} from "react";
import {CalendarDays,Gift,PauseCircle,PlayCircle,Plus,Tag,Trash2,Sparkles} from "lucide-react";
import {api,errorText} from "./api";
import "./offers.css";

type Offer={id:string;title:string;description:string;festival:string;offer_type:"PERCENT"|"AMOUNT"|"FREE_FUEL"|"BONUS_POINTS";value:number;min_amount_paise:number;fuel_name:string|null;starts_at:string;ends_at:string;active:boolean};
const localDate=(d:Date)=>{const p=(n:number)=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};
const moneyValue=(v:number)=>`₹${(v/100).toLocaleString("en-IN")}`;
function label(o:Offer){if(o.offer_type==="PERCENT")return `${o.value}% OFF`;if(o.offer_type==="AMOUNT")return `${moneyValue(o.value)} OFF`;if(o.offer_type==="FREE_FUEL")return `${o.value} ml FREE`;return `+${o.value} BONUS POINTS`}
function toIso(value:string){return new Date(value).toISOString()}
export function OffersScreen({notify}:{notify:(s:string)=>void}){
 const[rows,setRows]=useState<Offer[]>([]),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Offer|null>(null);
 const load=()=>api<Offer[]>("/offers?all=true").then(setRows);
 useEffect(()=>{void load().catch(e=>notify(errorText(e)))},[]);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const d=new FormData(e.currentTarget),offerType=String(d.get("offer_type")),rawValue=Number(d.get("value")),payload={title:String(d.get("title")),description:String(d.get("description")||""),festival:String(d.get("festival")||""),offer_type:offerType,value:offerType==="AMOUNT"?Math.round(rawValue*100):rawValue,min_amount_paise:Math.round(Number(d.get("min_amount")||0)*100),fuel_name:String(d.get("fuel_name")||"")||null,starts_at:toIso(String(d.get("starts_at"))),ends_at:toIso(String(d.get("ends_at"))),active:d.get("active")!==null};try{if(editing)await api(`/offers/${editing.id}`,payload);else await api("/offers",payload);setEditing(null);e.currentTarget.reset();await load();notify(editing?"Offer updated":"Festival offer published")}catch(err){notify(errorText(err))}finally{setBusy(false)}};
 const begin=(o:Offer)=>{setEditing(o);requestAnimationFrame(()=>document.getElementById("offer-form")?.scrollIntoView({behavior:"smooth",block:"start"}))};
 return <div className="offers-page"><section className="offers-hero"><div><p className="eyebrow">MARKETING & CUSTOMER OFFERS</p><h2><Sparkles/> Festival offers</h2><p>Create Holi, Diwali, New Year, Independence Day and custom station promotions. Active offers appear automatically in the Vehicle Owner portal.</p></div><div className="offer-hero-icon"><Gift/></div></section>
 <section id="offer-form" className="panel offer-editor"><div className="offer-section-title"><div><span className="offer-icon"><Plus/></span><div><h3>{editing?"Edit offer":"Create a new offer"}</h3><p>Publish a promotion with a start/end window and clear customer benefit.</p></div></div>{editing&&<button onClick={()=>setEditing(null)}>Cancel edit</button>}</div>
 <form key={editing?.id??"new"} onSubmit={submit}><div className="offer-grid"><label>Offer title<input name="title" defaultValue={editing?.title??""} placeholder="Holi Fuel Bonanza" required maxLength={120}/></label><label>Festival / occasion<input name="festival" defaultValue={editing?.festival??""} placeholder="Holi" maxLength={60}/></label><label>Offer type<select name="offer_type" defaultValue={editing?.offer_type??"PERCENT"}><option value="PERCENT">Percentage discount</option><option value="AMOUNT">Flat ₹ discount</option><option value="FREE_FUEL">Free fuel</option><option value="BONUS_POINTS">Bonus loyalty points</option></select></label><label>Value<input name="value" type="number" min="1" max={editing?.offer_type==="PERCENT"?100:1000000} defaultValue={editing?(editing.offer_type==="AMOUNT"?editing.value/100:editing.value):10} required/></label><label>Minimum bill (₹)<input name="min_amount" type="number" min="0" step="1" defaultValue={editing?editing.min_amount_paise/100:0}/></label><label>Fuel (optional)<input name="fuel_name" defaultValue={editing?.fuel_name??""} placeholder="Petrol / Diesel / CNG" maxLength={60}/></label><label>Starts<input name="starts_at" type="datetime-local" defaultValue={editing?localDate(new Date(editing.starts_at)):localDate(new Date())} required/></label><label>Ends<input name="ends_at" type="datetime-local" defaultValue={editing?localDate(new Date(editing.ends_at)):localDate(new Date(Date.now()+7*86400000))} required/></label></div><label>Description<textarea name="description" defaultValue={editing?.description??""} placeholder="Celebrate Holi with 10% off on fuel above ₹1,000." maxLength={500} rows={3}/></label><div className="offer-form-actions"><label className="offer-toggle"><input name="active" type="checkbox" defaultChecked={editing?.active??true}/><span>Publish immediately</span></label><button className="primary" disabled={busy}>{busy?(editing?"Saving…":"Publishing…"):(editing?"Save changes":"Publish offer")}</button></div></form></section>
 <section className="offer-list"><div className="offer-list-head"><div><h3>Offers & campaigns</h3><p>Manage what vehicle owners see in their Offers tab.</p></div><span>{rows.filter(o=>o.active).length} active</span></div>{rows.length===0?<div className="empty"><span>🏷️</span><h3>No offers yet</h3><p>Create your first festival promotion above.</p></div>:rows.map(o=><article className={`offer-card ${o.active?"":"is-off"}`} key={o.id}><div className="offer-card-top"><div className="festival-chip"><Tag/> {o.festival||"Station offer"}</div><span className={o.active?"status-pill live":"status-pill"}>{o.active?"LIVE":"PAUSED"}</span></div><h4>{o.title}</h4><p>{o.description||"Special offer for FuelPulse customers."}</p><strong className="offer-value">{label(o)}</strong><div className="offer-meta"><span><CalendarDays/> {new Date(o.starts_at).toLocaleDateString("en-IN")} – {new Date(o.ends_at).toLocaleDateString("en-IN")}</span>{o.min_amount_paise>0&&<span>Min. {moneyValue(o.min_amount_paise)}</span>}{o.fuel_name&&<span>{o.fuel_name}</span>}</div><div className="offer-actions"><button onClick={()=>begin(o)}><Tag/> Edit</button><button onClick={async()=>{try{await api(`/offers/${o.id}`,{active:!o.active});await load();notify(o.active?"Offer paused":"Offer published")}catch(e){notify(errorText(e))}}}>{o.active?<><PauseCircle/> Pause</>:<><PlayCircle/> Publish</>}</button><button className="danger" onClick={async()=>{if(!confirm(`Delete ${o.title}?`))return;try{await api(`/offers/${o.id}/delete`,{});await load();notify("Offer deleted")}catch(e){notify(errorText(e))}}}><Trash2/> Delete</button></div></article>)}</section></div>;
}
